apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
  namespace: k8s-scaling
  labels:
    conference: keda-webinar
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
      - name: web
        image: nginx:latest
        resources:
          requests:
            memory: 32Mi
            cpu: 25m
          limits:
            memory: 64Mi
            cpu: 50m
